# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Snapchat' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod ‘Firebase’
pod 'Firebase/Storage'	
pod 'Firebase/Auth'	
pod 'Firebase/RemoteConfig'	
pod 'Firebase/Crash'	
pod 'Firebase/DynamicLinks'	
pod 'Firebase/Invites'	
pod 'Firebase/Database'	
pod 'Firebase/Messaging'	
pod 'Firebase/AdMob'	
pod 'Firebase/Core'	

  # Pods for Snapchat

end
